const PANEL_DEFAULTS = Object.freeze({ files: { open: true, size: 220 }, editor: { open: true, size: null }, agent: { open: true, size: 360 } });
export function createWorkroomModel({ projectId, missionId = null, returnPath = '/' } = {}) {
  if (!projectId) throw new Error('Workroom requires projectId');
  const panels = Object.fromEntries(Object.entries(PANEL_DEFAULTS).map(([key, value]) => [key, { ...value }])); const openFiles = []; let activeFile = null;
  return Object.freeze({
    setPanel(name, open) { if (!panels[name]) throw new Error(`Unknown Workroom panel: ${name}`); panels[name].open = Boolean(open); },
    setPanelSize(name, size) { if (!panels[name]) throw new Error(`Unknown Workroom panel: ${name}`); const number = Number(size); if (!Number.isFinite(number) || number < 160 || number > 900) throw new Error('Panel size out of bounds'); panels[name].size = number; },
    openFile(path) { const value = String(path ?? '').trim(); if (!value) throw new Error('File path is required'); if (!openFiles.includes(value)) openFiles.push(value); activeFile = value; },
    closeFile(path) { const index = openFiles.indexOf(String(path)); if (index >= 0) openFiles.splice(index, 1); if (activeFile === path) activeFile = openFiles.at(-1) ?? null; },
    snapshot() { return Object.freeze({ projectId: String(projectId), missionId: missionId ? String(missionId) : null, returnPath: String(returnPath || '/'), panels: Object.freeze(Object.fromEntries(Object.entries(panels).map(([key, value]) => [key, Object.freeze({ ...value })]))), openFiles: Object.freeze([...openFiles]), activeFile }); },
  });
}

const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]);
export function renderWorkroomView(snapshot) {
  const fileRows = snapshot.openFiles.length ? snapshot.openFiles.map((path) => `<button type="button" data-workroom-file="${escapeHtml(path)}" aria-current="${snapshot.activeFile === path}"><span>JS</span><strong>${escapeHtml(path.split('/').at(-1))}</strong></button>`).join('') : `<div class="workroom-empty"><span>⌘P</span><p>Open a file or use repository search to begin.</p></div>`;
  return `<section class="workroom-view" data-project-id="${escapeHtml(snapshot.projectId)}"><header class="workroom-header"><div><a href="#${escapeHtml(snapshot.returnPath)}" data-route="${escapeHtml(snapshot.returnPath)}">← Back to Mission</a><h1>Studio</h1><p>Files, terminal, diffs, and live agent work in one focused surface.</p></div><div><button type="button" data-workroom-action="command">⌘ Command</button><button type="button" data-workroom-action="terminal">＋ Terminal</button></div></header><div class="workroom-tabs"><button aria-pressed="true">Editor</button><button>Changes</button><button>Preview</button><span></span><button>Layout</button></div><div class="workroom-grid" data-active-file="${escapeHtml(snapshot.activeFile ?? '')}"><aside class="workroom-files" data-panel="files" data-open="${snapshot.panels.files.open}"><header><strong>Files</strong><button>•••</button></header><label><span>⌕</span><input type="search" placeholder="Filter files"></label><div>${fileRows}</div></aside><main class="workroom-editor" data-panel="editor" data-open="${snapshot.panels.editor.open}"><header>${snapshot.activeFile ? `<span>${escapeHtml(snapshot.activeFile)}</span><button>×</button>` : '<span>No file open</span>'}</header><div>${snapshot.activeFile ? `<div class="editor-placeholder"><code>${escapeHtml(snapshot.activeFile)}</code><p>Editor host is ready for the selected file.</p></div>` : `<div class="editor-welcome"><span>N</span><h2>Nolane Studio</h2><p>Open a file, inspect a diff, or ask the agent to navigate the repository.</p><div><kbd>⌘P</kbd><span>Quick open</span><kbd>⌘⇧F</kbd><span>Search</span></div></div>`}</div></main><aside class="workroom-agent" aria-label="Agent / Terminal" data-panel="agent" data-open="${snapshot.panels.agent.open}"><header><div><button aria-pressed="true">Agent</button><button>Terminal</button></div><button>•••</button></header><div class="workroom-agent__body"><div class="agent-state-orb"><span></span></div><strong>Agent is ready</strong><p>Start or attach a mission to see file reads, commands, tools, and verification here.</p></div><footer><textarea placeholder="Steer the agent…"></textarea><button>↑</button></footer></aside></div><footer class="workroom-statusbar"><span>main</span><span>0 errors</span><span>0 warnings</span><i></i><span>Local</span><span>UTF-8</span></footer></section>`;
}
