'use strict';

const path = require('node:path');

const repository = process.env.GITHUB_REPOSITORY || process.env.NOLANE_GITHUB_REPOSITORY || 'Nolane-x/Nolane-agent';
const [owner, repo] = repository.split('/');
if (!owner || !repo) throw new Error('NOLANE_GITHUB_REPOSITORY must be owner/repo');

module.exports = {
  appId: 'com.nolane.agent',
  productName: 'Nolane Agent',
  copyright: 'Copyright © 2026 Nolane Agent contributors',
  asar: true,
  electronVersion: '43.2.0',
  compression: 'maximum',
  artifactName: 'NolaneAgent-Setup-${version}-${arch}.${ext}',
  directories: { output: 'release/installer', buildResources: 'build' },
  files: [
    'src/**/*',
    '!src/release/**/*',
    'src/release/dependency-preflight-service.mjs',
    'desktop/**/*',
    'ui/**/*',
    'ui-v3/**/*',
    'ui-dist/**/*',
    'config/product-identity.json',
    'config/release-identity.json',
    'config/update.json',
    'config/nolane-agent-update-public.pem',
    'vendor/forge-os/src/**/*',
    'vendor/forge-os/capabilities-v2/**/*',
    'vendor/forge-os/providers/**/*',
    'vendor/forge-os/skills-v2/**/*',
    'vendor/forge-os/skills/**/*',
    'vendor/forge-os/config/skill-flow.mjs',
    'vendor/forge-os/package.json',
    'vendor/forge-os/LICENSE',
    'native/**/*',
    'LICENSE',
    'THIRD_PARTY_NOTICES.md',
    '!tests/**/*',
    '!scripts/**/*',
    '!requirements/**/*',
    '!docs/**/*',
    '!release/**/*',
    '!data/**/*',
    '!vendor/nolane_native-agent/**',
    '!vendor/nolane_native-agent.manifest.json',
    '!src/nolane_native/**',
  ],
  asarUnpack: ['native/**/*'],
  extraMetadata: { main: 'desktop/main.cjs', productName: 'Nolane Agent' },
  win: {
    target: [{ target: 'nsis', arch: ['x64'] }],
    executableName: 'NolaneAgent',
    electronUpdaterCompatibility: '>=2.16',
    requestedExecutionLevel: 'asInvoker',
    verifyUpdateCodeSignature: process.env.NOLANE_VERIFY_AUTHENTICODE !== 'false',
    publisherName: process.env.NOLANE_WINDOWS_PUBLISHER || undefined,
  },
  nsis: {
    guid: 'd4f38ef8-b26d-4fc8-9b83-31a988f96251',
    oneClick: false,
    perMachine: false,
    allowElevation: true,
    allowToChangeInstallationDirectory: false,
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'Nolane Agent',
    uninstallDisplayName: 'Nolane Agent',
    deleteAppDataOnUninstall: false,
    differentialPackage: true,
    packElevateHelper: true,
    include: path.join(__dirname, 'build', 'installer.nsh'),
  },
  mac: {
    target: [{ target: 'dmg', arch: ['x64'] }, { target: 'zip', arch: ['x64'] }],
    artifactName: 'NolaneAgent-${version}-${arch}.${ext}',
    category: 'public.app-category.developer-tools',
  },
  linux: {
    target: [{ target: 'AppImage', arch: ['x64'] }, { target: 'deb', arch: ['x64'] }],
    artifactName: 'NolaneAgent-${version}-${arch}.${ext}',
    category: 'Development',
  },
  publish: [{ provider: 'github', owner, repo, channel: '${channel}', releaseType: 'draft' }],
};
