function req(value, name) { const text = String(value ?? '').trim(); if (!text) throw new TypeError(`${name} is required`); return text; }
function clone(value) { return structuredClone(value); }
export class CloudQueue {
  constructor({ clock = () => Date.now(), maxAttempts = 3, maxPayloadBytes = 256_000, storage = null } = {}) { this.clock = clock; this.maxAttempts = Math.max(1, maxAttempts); this.maxPayloadBytes = maxPayloadBytes; this.storage = storage; const restored = storage?.loadAll?.() ?? []; this.jobs = new Map(restored.map((job) => [job.id, job])); this.sequence = restored.reduce((max, job) => Math.max(max, Number(job.sequence) || 0), 0); }
  enqueue(input = {}) { const id = req(input.id, 'job id'); if (this.jobs.has(id)) throw Object.assign(new Error('Job already exists'), { statusCode: 409 }); const payload = clone(input.payload ?? {}); if (Buffer.byteLength(JSON.stringify(payload)) > this.maxPayloadBytes) throw Object.assign(new Error('Job payload too large'), { statusCode: 413 }); const job = { id, organizationId: req(input.organizationId, 'organizationId'), workspaceId: req(input.workspaceId, 'workspaceId'), priority: Number(input.priority ?? 0), payload, state: 'queued', attempts: 0, sequence: ++this.sequence, fencingToken: 0, lease: null, createdAt: this.clock(), updatedAt: this.clock(), error: null, result: null }; this.jobs.set(id, job); this.#persist(job); return clone(job); }
  get(id) { const job = this.jobs.get(String(id)); return job ? clone(job) : null; }
  #persist(job) { this.storage?.save?.(job); }
  lease({ organizationId, workerId, leaseMs = 30_000 } = {}) { const org = req(organizationId, 'organizationId'); const worker = req(workerId, 'workerId'); const now = this.clock(); const boundedLeaseMs = Math.max(100, Number(leaseMs) || 30_000); if (typeof this.storage?.leaseNext === 'function') { const leased = this.storage.leaseNext({ organizationId: org, workerId: worker, leaseMs: boundedLeaseMs, now }); if (!leased) return null; this.jobs.set(leased.id, leased); return { job: clone(leased), fencingToken: leased.fencingToken, leaseExpiresAt: leased.lease.expiresAt }; } const candidate = [...this.jobs.values()].filter((j) => j.organizationId === org && j.state === 'queued').sort((a,b) => b.priority - a.priority || a.sequence - b.sequence)[0]; if (!candidate) return null; candidate.state = 'leased'; candidate.attempts += 1; candidate.fencingToken += 1; candidate.lease = { workerId: worker, expiresAt: now + boundedLeaseMs }; candidate.updatedAt = now; this.#persist(candidate); return { job: clone(candidate), fencingToken: candidate.fencingToken, leaseExpiresAt: candidate.lease.expiresAt }; }
  #leased(input) { const job = this.jobs.get(req(input.jobId, 'jobId')); if (!job || job.state !== 'leased' || job.lease?.workerId !== req(input.workerId, 'workerId') || job.fencingToken !== Number(input.fencingToken)) throw Object.assign(new Error('Stale or invalid fencing token'), { statusCode: 409, code: 'stale-fencing-token' }); return job; }
  heartbeat(input = {}) { const job = this.#leased(input); job.lease.expiresAt = this.clock() + Math.max(100, Number(input.leaseMs) || 30_000); job.updatedAt = this.clock(); this.#persist(job); return clone(job); }
  complete(input = {}) { const job = this.#leased(input); job.state = 'completed'; job.result = clone(input.result ?? {}); job.lease = null; job.updatedAt = this.clock(); this.#persist(job); return clone(job); }
  fail(input = {}) { const job = this.#leased(input); job.error = clone(input.error ?? { code: 'worker-failed' }); job.lease = null; job.updatedAt = this.clock(); job.state = input.retryable !== false && job.attempts < this.maxAttempts ? 'queued' : 'dead-letter'; this.#persist(job); return clone(job); }
  cancel({ jobId, organizationId } = {}) { const job = this.jobs.get(req(jobId, 'jobId')); if (!job || job.organizationId !== req(organizationId, 'organizationId')) throw Object.assign(new Error('Job not found'), { statusCode: 404 }); if (['completed','dead-letter','cancelled'].includes(job.state)) return clone(job); job.state = 'cancelled'; job.lease = null; job.updatedAt = this.clock(); this.#persist(job); return clone(job); }
  requeueExpired() { const now = this.clock(); let count = 0; for (const job of this.jobs.values()) { if (job.state === 'leased' && job.lease.expiresAt <= now) { job.lease = null; job.state = job.attempts < this.maxAttempts ? 'queued' : 'dead-letter'; job.updatedAt = now; this.#persist(job); count += 1; } } return count; }
  metrics({ organizationId } = {}) { const jobs = [...this.jobs.values()].filter((j) => !organizationId || j.organizationId === organizationId); const queued = jobs.filter((j) => j.state === 'queued'); return { queueDepth: queued.length, oldestJobAgeMs: queued.length ? this.clock() - Math.min(...queued.map((j) => j.createdAt)) : 0, leased: jobs.filter((j) => j.state === 'leased').length, deadLetter: jobs.filter((j) => j.state === 'dead-letter').length }; }
}
