import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generateFeatureAudit } from '../scripts/audit-feature-checklist.mjs';
import { VERSION } from '../src/version.mjs';

test('feature audit covers every checklist item and never marks missing evidence as verified', async (t) => {
  const output = await mkdtemp(path.join(os.tmpdir(), 'forge-feature-audit-'));
  t.after(() => rm(output, { recursive: true, force: true }));
  const report = await generateFeatureAudit({ sourceFile: 'docs/source-feature-checklist-vn.txt', outputDirectory: output });
  assert.equal(report.sections.length, 28);
  assert.equal(report.totalItems, 790);
  assert.equal(report.sections[11].items.some((item) => item.text === 'Hỗ trợ AGENTS.md'), true);
  assert.equal(report.sections[11].items.some((item) => item.text === 'Hỗ trợ CLAUDE.md'), true);
  assert.equal(report.sections[4].items[0].text, 'Nhận yêu cầu người dùng');
  assert.equal(report.sections[19].items[0].text, 'Sandbox theo từng task');
  assert.equal(report.sections[22].items[0].text, 'Quyền đọc file');
  for (const item of report.sections.flatMap((section) => section.items)) {
    assert.match(item.id, /^\d+\.\d+$/);
    assert.ok(['verified_source_test', 'partial', 'external_gate', 'not_implemented'].includes(item.status));
    if (item.status === 'verified_source_test') assert.ok(item.evidence.some((file) => file.startsWith('tests/')));
  }
  const byText = new Map(report.sections.flatMap((section) => section.items).map((item) => [item.text, item]));
  assert.equal(byText.get('CLI tương tác').status, 'verified_source_test');
  assert.equal(byText.get('CLI không tương tác').status, 'verified_source_test');
  assert.equal(byText.get('SDK cho Python').status, 'verified_source_test');
  assert.equal(byText.get('SDK cho TypeScript').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ AGENTS.md').status, 'verified_source_test');
  for (const instructionItem of ['Hỗ trợ hướng dẫn toàn cục', 'Hỗ trợ hướng dẫn theo thư mục', 'Hỗ trợ hướng dẫn theo ngôn ngữ', 'Hỗ trợ hướng dẫn theo tác vụ', 'Hỗ trợ kế thừa hướng dẫn', 'Hỗ trợ ưu tiên hướng dẫn', 'Phát hiện hướng dẫn mâu thuẫn', 'Báo hướng dẫn không hợp lệ', 'Có schema kiểm tra hướng dẫn', 'Cho phép import tài liệu khác']) assert.equal(byText.get(instructionItem).status, 'verified_source_test', instructionItem);
  assert.equal(report.sections.find((section) => section.number === 12).summary.partial, 0);
  for (const discoveryItem of ['Xác định framework', 'Xác định package manager', 'Xác định hệ thống build', 'Xác định test runner', 'Xác định formatter', 'Xác định linter', 'Xác định type checker', 'Xác định cấu trúc monorepo', 'Xác định entry point', 'Xác định CI workflow', 'Xác định Docker setup', 'Xác định migration system', 'Xác định database', 'Xác định API style', 'Xác định convention đặt tên', 'Xác định kiến trúc ứng dụng', 'Xác định lệnh deploy', 'Xác định biến môi trường cần thiết']) assert.equal(byText.get(discoveryItem).status, 'verified_source_test', discoveryItem);
  assert.equal(report.sections.find((section) => section.number === 11).summary.partial, 0);
  assert.equal(byText.get('Trình xem dependency graph').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ semantic search').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ AST query').status, 'verified_source_test');
  assert.equal(byText.get('Patch theo AST').status, 'verified_source_test');
  assert.equal(byText.get('Lập chỉ mục inheritance graph').status, 'verified_source_test');
  assert.equal(byText.get('Lập chỉ mục issue liên quan').status, 'verified_source_test');
  assert.equal(byText.get('Trình duyệt tích hợp').status, 'verified_source_test');
  assert.equal(byText.get('Trình quản lý secrets').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ tree-sitter').status, 'external_gate');
  assert.equal(byText.get('Hỗ trợ mở worktree trong IDE').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ chuyển task sang local').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ language server').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ definition search').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ reference search').status, 'verified_source_test');
  assert.equal(byText.get('Đọc theo khoảng dòng').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ stdin').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ Podman').status, 'external_gate');
  assert.equal(byText.get('Hỗ trợ Windows Job Objects').status, 'external_gate');
  assert.equal(byText.get('Hỗ trợ macOS sandbox').status, 'external_gate');
  for (const gitCompletionItem of ['Đọc remote', 'Tạo checkpoint commit', 'Commit thay đổi agent', 'Viết commit message', 'Stage file chọn lọc', 'Không stage file bí mật', 'Không commit artifact dư thừa', 'Giải quyết conflict', 'Hiển thị conflict cho người dùng', 'Ghi test đã chạy', 'Ghi rủi ro còn lại', 'Theo dõi thay đổi giữa các agent', 'Phát hiện file bị nhiều agent sửa', 'Phát hiện conflict sớm', 'Review từng diff trước merge']) assert.equal(byText.get(gitCompletionItem).status, 'verified_source_test', gitCompletionItem);
  for (const atomicPatchItem of ['Chỉnh nhiều file nguyên tử', 'Chạy formatter sau sửa', 'Không format toàn dự án vô cớ', 'Không sửa generated code', 'Không xóa comment quan trọng', 'Có giới hạn số file mỗi lượt', 'Có giới hạn số dòng mỗi lượt', 'Hỗ trợ conflict markers', 'Sinh patch tối thiểu', 'Đo độ lớn patch']) assert.equal(byText.get(atomicPatchItem).status, 'verified_source_test', atomicPatchItem);
  for (const commandGovernanceItem of ['Hỗ trợ pseudo-terminal', 'Hỗ trợ argument filtering', 'Hỗ trợ shell escaping', 'Hỗ trợ Windows PowerShell', 'Hỗ trợ CMD khi cần', 'Hỗ trợ Bash', 'Hỗ trợ WSL', 'Không chạy server không quản lý PID', 'Lệnh thay đổi hệ thống', 'Lệnh thay đổi quyền', 'Lệnh chạy mã tải từ internet', 'Lệnh chạy với administrator', 'Lệnh thay đổi firewall', 'Lệnh khởi động service', 'Lệnh dừng service', 'Lệnh gửi dữ liệu ra ngoài', 'Chống approval fatigue', 'Chặn SQL nguy hiểm', 'Chặn upload dữ liệu nhạy cảm', 'Không lưu API key trong chat']) assert.equal(byText.get(commandGovernanceItem).status, 'verified_source_test', commandGovernanceItem);
  for (const planningEvidenceItem of ['Yêu cầu người dùng khi cần', 'Phát hiện thông tin thiếu', 'Ước lượng phạm vi', 'Kiểm tra lỗi bảo mật', 'Kiểm tra tài liệu', 'Xác định rủi ro từng bước', 'Xác định file dự kiến sửa', 'Xác định công cụ cần dùng', 'Xác định agent con cần gọi', 'Lưu lý do thay đổi kế hoạch', 'Không lập kế hoạch quá chi tiết', 'Không cho phép bước mơ hồ', 'Tìm test liên quan', 'Tìm config liên quan', 'Tìm trong tài liệu', 'Tóm tắt kết quả']) assert.equal(byText.get(planningEvidenceItem).status, 'verified_source_test', planningEvidenceItem);
  for (const localOperationsItem of ['Trình xem ảnh', 'Trình xem call graph', 'Trình xem Git history', 'Trình quản lý chi phí', 'Nút sửa câu lệnh trước khi chạy', 'Nút chuyển sang điều khiển thủ công', 'Giải phóng sandbox', 'Giữ sandbox khi cần tiếp tục', 'Làm sạch nội dung độc hại', 'Cache có kiểm soát']) assert.equal(byText.get(localOperationsItem).status, 'verified_source_test', localOperationsItem);
  for (const runtimeReadinessItem of ['Thêm extension IDE sau khi lõi ổn định','Thêm desktop app khi cần đa agent','Thêm cloud agent ở giai đoạn cuối','Mọi tác vụ phải có giới hạn tài nguyên','Tách phần suy nghĩ khỏi phần thực thi','Ưu tiên hệ thống đơn giản nhưng mở rộng được','Giải thích kiến trúc dự án','Sửa test thất bại','Sửa lỗi dependency','Giải quyết conflict Git','Tạo commit','Review pull request','Kiểm tra bảo mật','Cập nhật tài liệu','Chạy nhiều tác vụ song song','IDE extension','Commit nếu được phép','Kiểm tra Docker daemon','Kiểm tra quyền mount','Kiểm tra socket escape']) assert.equal(byText.get(runtimeReadinessItem).status, 'verified_source_test', runtimeReadinessItem);
  assert.equal(byText.get('Merge').status, 'verified_source_test');
  assert.equal(byText.get('Rebase').status, 'verified_source_test');
  assert.equal(byText.get('Cherry-pick').status, 'verified_source_test');
  assert.equal(byText.get('Revert').status, 'verified_source_test');
  assert.equal(byText.get('Reset an toàn').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ GitLab').status, 'external_gate');
  assert.equal(byText.get('Hỗ trợ Bitbucket').status, 'external_gate');
  assert.equal(byText.get('Tìm regex').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ paging').status, 'verified_source_test');
  assert.equal(byText.get('Hỗ trợ reverse patch').status, 'verified_source_test');
  assert.equal(byText.get('Quyền administrator').status, 'verified_source_test');
  assert.equal(byText.get('Quyền theo argument').status, 'verified_source_test');
  assert.equal(byText.get('Chặn giả mạo test thành công').status, 'verified_source_test');
  assert.equal(byText.get('Phát hiện secret trong terminal').status, 'verified_source_test');
  assert.equal(byText.get('Quét malware output').status, 'verified_source_test');
  assert.equal(byText.get('Kiểm tra dependency tải về').status, 'verified_source_test');
  assert.equal(byText.get('Hợp nhất theo dependency order').status, 'verified_source_test');
  assert.equal(byText.get('Rebase worktree trước merge').status, 'verified_source_test');
  assert.equal(byText.get('Chạy test sau merge').status, 'verified_source_test');
  assert.deepEqual(report.summary, { verified_source_test: 734, partial: 0, external_gate: 56, not_implemented: 0 });
  const unresolved = report.summary.partial + report.summary.external_gate + report.summary.not_implemented;
  assert.equal(report.summary.verified_source_test + unresolved, report.totalItems, 'every checklist item must have exactly one status');
  assert.equal(unresolved, report.totalItems - report.summary.verified_source_test);
  assert.ok(report.summary.external_gate > 0, 'external production gates must remain explicit instead of being inferred as verified');
  assert.equal(report.summary.not_implemented, 0, 'all previously missing items must now have source evidence or an explicit external gate');
  const json = JSON.parse(await readFile(path.join(output, `feature-audit-${VERSION}.json`), 'utf8'));
  assert.equal(json.totalItems, 790);
  assert.match(await readFile(path.join(output, `FEATURE-COMPLETENESS-AUDIT-${VERSION}.md`), 'utf8'), /không đồng nghĩa đã vận hành production/i);
});

test('feature audit output is reproducible and does not dirty the source tree on rerun', async (t) => {
  const output = await mkdtemp(path.join(os.tmpdir(), 'forge-feature-audit-repro-'));
  t.after(() => rm(output, { recursive: true, force: true }));
  await generateFeatureAudit({ sourceFile: 'docs/source-feature-checklist-vn.txt', outputDirectory: output });
  const firstJson = await readFile(path.join(output, `feature-audit-${VERSION}.json`), 'utf8');
  const firstMarkdown = await readFile(path.join(output, `FEATURE-COMPLETENESS-AUDIT-${VERSION}.md`), 'utf8');
  await new Promise((resolve) => setTimeout(resolve, 5));
  await generateFeatureAudit({ sourceFile: 'docs/source-feature-checklist-vn.txt', outputDirectory: output });
  assert.equal(await readFile(path.join(output, `feature-audit-${VERSION}.json`), 'utf8'), firstJson);
  assert.equal(await readFile(path.join(output, `FEATURE-COMPLETENESS-AUDIT-${VERSION}.md`), 'utf8'), firstMarkdown);
});
