import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyForensicRecoveryCheckpoint4 } from '../src/forensics/recovery-checkpoint-4.mjs';
import { createModelArtifact } from '../src/small-model/model-artifact.mjs';
import { canonicalSha256 } from '../vendor/forge-os/src/core/canonical-json.mjs';

const H=(c)=>c.repeat(64);
const specialists=['context-scorer','patch-ranker','risk-classifier','test-selector'];
function artifact(specialist,index){ return createModelArtifact({specialist,datasetReceiptSha256:H(String(index+1)),trainingConfig:{seed:`cp4-${specialist}`},model:{schema:'nolane.small-model.linear-policy.v1',labels:['a','b'],dimensions:4,weights:[[0,1,0,0],[0,-1,0,0]],biases:[0,0],training:{examples:24,epochs:5,seed:`cp4-${specialist}`,lossHistory:[1,.2]}}}); }
function benchmark(a,specialist){ const evaluation={schema:'nolane.small-model.specialist-evaluation.v1',artifactSha256:a.artifactSha256,specialist,independent:true,heldOut:true,examples:12,correct:12,accuracy:1,abstentions:0,safetyViolations:0,baselineSafetyViolations:0,thresholds:{minAccuracy:.95},confusion:{'a->a':6,'b->b':6},allowed:true,claims:{boundedHeldOutEvidence:true,generalCodingIntelligence:false,competitorSuperiority:false},receiptSha256:H('e')}; const base={schema:'nolane.small-model.bootstrap-specialist-benchmark.v1',specialist,artifactSha256:a.artifactSha256,datasetReceiptSha256:H('f'),validation:evaluation,heldOut:evaluation,resourceProfile:{runtime:'node-js-linear-policy',dimensions:4,parameters:10},claims:{boundedSpecialistModel:true,generalCodingIntelligence:false,frontierParity:false,competitorSuperiority:false}}; return {...base,receiptSha256:canonicalSha256(base)}; }
function validInput(overrides={}){ const artifacts={};const benchmarks={};const artifactSha256BySpecialist={};const benchmarkReceiptSha256BySpecialist={}; specialists.forEach((s,i)=>{artifacts[s]=artifact(s,i);benchmarks[s]=benchmark(artifacts[s],s);artifactSha256BySpecialist[s]=artifacts[s].artifactSha256;benchmarkReceiptSha256BySpecialist[s]=benchmarks[s].receiptSha256;}); const suiteBase={schema:'nolane.small-model.bootstrap-specialist-suite-verification.v1',status:'pass',artifactSha256BySpecialist,benchmarkReceiptSha256BySpecialist}; const suiteVerification={...suiteBase,receiptSha256:canonicalSha256(suiteBase)}; return {custody:{records:[{id:'nolane-native-canonical',status:'missing'}]},truthLedger:{total:8548,resolved:1353,unresolved:7195,completeParityEligible:false},assertionBaseline:{receiptSha256:H('a'),coverage:{summary:{requirementsTotal:48,requirementsBound:48,requirementsUnbound:0,requirementsPositiveBound:48,requirementsNegativeBound:48,overBroadTestFiles:0},certifiable:true}},masterAudit:{receiptSha256:H('b'),summary:{requirementsTotal:1460,assertionVerified:955,assertionUnbound:417,externalUnverified:88,overBroadTestFiles:31,documentationOnlyEntrypoints:1,missingPositiveAssertions:0,missingNegativeAssertions:21}},suiteArtifacts:artifacts,suiteBenchmarks:benchmarks,suiteVerification,decisionReceipt:{schema:'nolane.small-model.specialist-decision-support.v1',status:'allow',allowed:true,requiresApproval:false,decisions:{context:{action:'support'},test:{action:'unit'},patch:{action:'accept'},risk:{action:'low'}},claims:{boundedDecisionSupport:true,generalCodingIntelligence:false,frontierParity:false,competitorSuperiority:false},receiptSha256:H('d')},claims:{completeParityClaimAllowed:false,comparativeSuperiorityClaimAllowed:false,windowsUiCertified:false,providerRealCertified:false,smallModelSuperintelligenceImplemented:false,allOriginalGoalsComplete:false},...overrides}; }

test('checkpoint 4 verifies evidence reduction and four real bounded specialists without broad claims',()=>{ const result=verifyForensicRecoveryCheckpoint4(validInput()); assert.equal(result.status,'pass'); assert.equal(result.masterLedger.assertionUnbound,417); assert.equal(result.masterLedger.assertionVerified,955); assert.equal(result.specialists.length,4); assert.equal(result.boundedSpecialistSuiteVerified,true); assert.equal(result.generalCodingIntelligenceClaimAllowed,false); assert.match(result.receiptSha256,/^[a-f0-9]{64}$/); });

test('checkpoint 4 rejects weak evidence, missing specialist artifacts, and unlocked claims',()=>{ assert.throws(()=>verifyForensicRecoveryCheckpoint4(validInput({masterAudit:{receiptSha256:H('b'),summary:{requirementsTotal:1460,assertionVerified:900,assertionUnbound:472,externalUnverified:88}}})),/unbound threshold/i); const input=validInput(); delete input.suiteArtifacts['risk-classifier']; assert.throws(()=>verifyForensicRecoveryCheckpoint4(input),/risk-classifier/i); assert.throws(()=>verifyForensicRecoveryCheckpoint4(validInput({claims:{completeParityClaimAllowed:false,comparativeSuperiorityClaimAllowed:true,windowsUiCertified:false,providerRealCertified:false,smallModelSuperintelligenceImplemented:false,allOriginalGoalsComplete:false}})),/protected claim/i); });
