import test from 'node:test';
import assert from 'node:assert/strict';
import { verifyForensicRecoveryCheckpoint5 } from '../src/forensics/recovery-checkpoint-5.mjs';
import { createModelArtifact } from '../src/small-model/model-artifact.mjs';
import { canonicalSha256 } from '../vendor/forge-os/src/core/canonical-json.mjs';

const H=(c)=>c.repeat(64);
const specialists=['tool-router','context-scorer','test-selector','patch-ranker','risk-classifier'];
function artifact(specialist,index){return createModelArtifact({specialist,datasetReceiptSha256:H(String(index+1)),trainingConfig:{seed:`cp5-${specialist}`},model:{schema:'nolane.small-model.linear-policy.v1',labels:['a','b'],dimensions:16,weights:[[0,1,...Array(14).fill(0)],[0,-1,...Array(14).fill(0)]],biases:[0,0],training:{examples:24,epochs:5,seed:`cp5-${specialist}`,lossHistory:[1,.2]}}});}
function evaluation(a,specialist){const base={schema:'nolane.small-model.specialist-evaluation.v1',artifactSha256:a.artifactSha256,specialist,independent:true,heldOut:true,examples:8,correct:8,accuracy:1,abstentions:0,safetyViolations:0,baselineSafetyViolations:0,thresholds:{minAccuracy:.8},confusion:{'a->a':4,'b->b':4},allowed:true,claims:{boundedHeldOutEvidence:true,generalCodingIntelligence:false,competitorSuperiority:false}};return {...base,receiptSha256:canonicalSha256(base)};}
function decision(status,allowed,requiresApproval){const base={schema:'nolane.small-model.repository-specialist-decision-support.v1',status,allowed,requiresApproval,decisions:{tool:{action:allowed?'read':'stop'},context:{action:allowed?'pin':'exclude'},test:{action:'unit'},patch:{action:allowed?'accept':'reject'},risk:{action:allowed?'low':'critical'}},policy:{},hiddenChainOfThoughtStored:false,claims:{boundedRepositoryDecisionSupport:true,generalCodingIntelligence:false,frontierParity:false,competitorSuperiority:false}};return {...base,receiptSha256:canonicalSha256(base)};}
function episode(index){const base={id:`ep-${index}`,kind:'verification',state:{testSha256:H('a'),sourceSha256ByPath:{'src/a.mjs':H('b')}},action:{type:'test',argv:['node','--test','tests/a.test.mjs'],shell:false},expectedEffect:{verifierExitCode:0},actualEffect:{changed:true,criterionDelta:1,informationGain:1},verifier:{valid:true,rewardHacking:false,exitCode:0},cost:{durationMs:1}};return {...base,receiptSha256:canonicalSha256(base)};}
function validInput(overrides={}){
 const episodes=Array.from({length:32},(_,i)=>episode(i));
 const trajectoryBase={schema:'nolane.small-model.repository-trajectory-dataset.v1',episodeCount:32,attemptCount:32,excludedCount:0,episodeIds:episodes.map(x=>x.id),episodeReceipts:episodes.map(x=>x.receiptSha256),episodesSha256:H('c'),collectionReceiptSha256:H('d')};
 const trajectoryDataset={...trajectoryBase,receiptSha256:canonicalSha256(trajectoryBase)};
 const artifacts={},benchmarks={},artifactSha256BySpecialist={},benchmarkReceiptSha256BySpecialist={};
 specialists.forEach((s,i)=>{const a=artifact(s,i),e=evaluation(a,s);artifacts[s]=a;const b={schema:'nolane.small-model.repository-specialist-benchmark.v1',specialist:s,artifactSha256:a.artifactSha256,datasetReceiptSha256:H('e'),validation:e,heldOut:e,resourceProfile:{runtime:'node',dimensions:16,parameters:34},lineage:{trajectoryDatasetReceiptSha256:trajectoryDataset.receiptSha256,observedEpisodes:32},claims:{boundedRepositorySpecialist:true,generalCodingIntelligence:false,frontierParity:false,competitorSuperiority:false}};benchmarks[s]={...b,receiptSha256:canonicalSha256(b)};artifactSha256BySpecialist[s]=a.artifactSha256;benchmarkReceiptSha256BySpecialist[s]=benchmarks[s].receiptSha256;});
 const suiteBase={schema:'nolane.small-model.repository-specialist-suite-verification.v1',status:'pass',trajectoryDatasetReceiptSha256:trajectoryDataset.receiptSha256,artifactSha256BySpecialist,benchmarkReceiptSha256BySpecialist,claims:{generalCodingIntelligence:false,competitorSuperiority:false}};
 return {custody:{records:[{id:'nolane-native-canonical',status:'missing'}]},truthLedger:{total:8548,resolved:1353,unresolved:7195,completeParityEligible:false},assertionBaseline:{receiptSha256:H('f'),coverage:{summary:{requirementsTotal:48,requirementsBound:48,requirementsUnbound:0,requirementsPositiveBound:48,requirementsNegativeBound:48,overBroadTestFiles:0},certifiable:true}},masterAudit:{receiptSha256:H('1'),summary:{requirementsTotal:1460,assertionVerified:1107,assertionUnbound:265,externalUnverified:88,overBroadTestFiles:29,missingNegativeAssertions:20}},trajectoryDataset,trajectoryEpisodes:episodes,suiteArtifacts:artifacts,suiteBenchmarks:benchmarks,suiteVerification:{...suiteBase,receiptSha256:canonicalSha256(suiteBase)},safeDecisionReceipt:decision('allow',true,false),unsafeDecisionReceipt:decision('blocked',false,true),claims:{completeParityClaimAllowed:false,comparativeSuperiorityClaimAllowed:false,windowsUiCertified:false,providerRealCertified:false,smallModelSuperintelligenceImplemented:false,allOriginalGoalsComplete:false},...overrides};
}

test('checkpoint 5 verifies exact bindings, real trajectories and five repository specialists without broad claims',()=>{const result=verifyForensicRecoveryCheckpoint5(validInput());assert.equal(result.status,'pass');assert.equal(result.masterLedger.assertionVerified,1107);assert.equal(result.masterLedger.assertionUnbound,265);assert.equal(result.repositoryTrajectories.episodes,32);assert.equal(result.specialists.length,5);assert.equal(result.repositorySpecialistSuiteVerified,true);assert.equal(result.generalCodingIntelligenceClaimAllowed,false);assert.match(result.receiptSha256,/^[a-f0-9]{64}$/);});

test('checkpoint 5 rejects weak evidence, trajectory tampering, missing specialists and unlocked claims',()=>{assert.throws(()=>verifyForensicRecoveryCheckpoint5(validInput({masterAudit:{receiptSha256:H('1'),summary:{requirementsTotal:1460,assertionVerified:1099,assertionUnbound:273,externalUnverified:88}}})),/verified threshold/i);const bad=validInput();bad.trajectoryEpisodes[0]={...bad.trajectoryEpisodes[0],receiptSha256:H('9')};assert.throws(()=>verifyForensicRecoveryCheckpoint5(bad),/episode receipt mismatch/i);const missing=validInput();delete missing.suiteArtifacts['tool-router'];assert.throws(()=>verifyForensicRecoveryCheckpoint5(missing),/tool-router/i);assert.throws(()=>verifyForensicRecoveryCheckpoint5(validInput({claims:{completeParityClaimAllowed:false,comparativeSuperiorityClaimAllowed:true,windowsUiCertified:false,providerRealCertified:false,smallModelSuperintelligenceImplemented:false,allOriginalGoalsComplete:false}})),/protected claim/i);});
