import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { NolaneNativeOrchestrationService } from '../src/nolane-native/orchestration-service.mjs';
import { createRoutes } from '../src/server/routes.mjs';

async function fixture(t) { const root = await mkdtemp(path.join(os.tmpdir(), 'nolane-wave13-production-')); t.after(() => rm(root, { recursive: true, force: true })); const service = new NolaneNativeOrchestrationService({ dataDir: path.join(root, '.data'), workspaceRoot: root, wave13RedirectAllowlist: ['http://127.0.0.1:49152/callback'] }); await service.open(); return service; }
const callFor = (service) => { const route = createRoutes({ nativeOrchestration: service }); return async ({ method = 'GET', pathname, body = null }) => { let status; let data = ''; const req = { method, forgePrincipal: { subject: 'alice' }, async *[Symbol.asyncIterator]() { if (body !== null) yield Buffer.from(JSON.stringify(body)); } }; const res = { writeHead(code) { status = code; }, end(chunk = '') { data += chunk; } }; await route(req, res, new URL(`http://local${pathname}`)); return { status, body: data ? JSON.parse(data) : null }; }; };

test('orchestration production-wires trust core wave13', async (t) => { const service = await fixture(t); service.registerNativeTrustOAuthProvider({ id: 'demo', authorizationUrl: 'https://auth.example/authorize' }); const begin = service.beginNativeTrustOAuth({ providerId: 'demo', profileId: 'p1', redirectUri: 'http://127.0.0.1:49152/callback' }); const complete = await service.completeNativeTrustOAuth({ state: begin.state, code: 'code', codeVerifier: begin.codeVerifier, exchange: async () => ({ credentialRef: 'vault:p1' }) }); assert.equal(complete.credentialRef, 'vault:p1'); service.grantNativeTrustProfile({ profileId: 'p1', permissions: ['tool:read'], credentialRef: 'vault:p1' }); assert.deepEqual(service.nativeTrustProfileStatus('p1').permissions, ['tool:read']); const invite = service.issueNativeTrustPairing({ profileId: 'p1', permissions: ['message:send'] }); assert.equal((await service.enrollNativeTrustPairing({ code: invite.code, deviceId: 'd1' })).state, 'active'); assert.equal(service.status().trustWave13.pairing.devices.length, 1); });

test('HTTP trust wave13 routes expose pairing, reauthentication and status', async (t) => { const service = await fixture(t); const call = callFor(service); const invite = await call({ method: 'POST', pathname: '/api/nolane/native-core/trust/wave13/pairing/issue', body: { profileId: 'p1', permissions: ['message:send'] } }); assert.equal(invite.status, 201); const enrolled = await call({ method: 'POST', pathname: '/api/nolane/native-core/trust/wave13/pairing/enroll', body: { code: invite.body.code, deviceId: 'd1' } }); assert.equal(enrolled.body.state, 'active'); const reauth = await call({ method: 'POST', pathname: '/api/nolane/native-core/trust/wave13/reauth', body: { profileId: 'p1', reason: 'expired' } }); assert.equal(reauth.body.reauthRequired, true); const status = await call({ pathname: '/api/nolane/native-core/trust/wave13/status' }); assert.equal(status.body.pairing.devices.length, 1); });
