import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHttpServer } from '../src/server/http-server.mjs';
import { ProviderRegistry } from '../src/providers/provider-registry.mjs';
import { StudioStore } from '../src/storage/studio-store.mjs';
import { SmallModelFoundationService } from '../src/small-model/foundation-service.mjs';

const auth = (options = {}) => ({ ...options, headers: { authorization: 'Bearer nolane-token', 'content-type': 'application/json', ...(options.headers ?? {}) } });
const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

test('authenticated checkpoint 8 HTTP workflow keeps compilation pending until explicit promotion', async (t) => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'nolane-checkpoint-8-http-'));
  await writeFile(path.join(root, 'index.html'), '<!doctype html>');
  const store = new StudioStore(path.join(root, 'studio.db')); t.after(() => store.close());
  const foundation = new SmallModelFoundationService();
  const service = await createHttpServer({ config: { host: '127.0.0.1', port: 0, authToken: 'nolane-token' }, store, providers: new ProviderRegistry(), missionRunner: {}, smallModelFoundation: foundation, uiRoot: root });
  t.after(() => service.close());
  t.after(() => rm(root, { recursive: true, force: true }));
  const statusUrl = `${service.url}/api/small-model/foundation/model/checkpoint-8/status`;
  assert.equal((await fetch(statusUrl)).status, 401);
  assert.equal((await (await fetch(statusUrl, auth())).json()).ready, false);
  const prepare = await fetch(`${service.url}/api/small-model/foundation/model/checkpoint-8/prepare`, auth({ method: 'POST', body: JSON.stringify({ root: projectRoot }) }));
  assert.equal(prepare.status, 201);
  const prepared = await prepare.json();
  assert.equal(prepared.status, 'pending-approval');
  const denied = await fetch(`${service.url}/api/small-model/foundation/model/checkpoint-8/promote`, auth({ method: 'POST', body: JSON.stringify({ bundleReceiptSha256: prepared.bundleReceiptSha256 }) }));
  assert.equal(denied.status, 500);
  const promote = await fetch(`${service.url}/api/small-model/foundation/model/checkpoint-8/promote`, auth({ method: 'POST', body: JSON.stringify({ bundleReceiptSha256: prepared.bundleReceiptSha256, approvedBy: 'checkpoint-owner' }) }));
  assert.equal(promote.status, 201);
  assert.equal((await promote.json()).promotions.length, 3);
  assert.equal((await (await fetch(statusUrl, auth())).json()).ready, true);
  const ast = await fetch(`${service.url}/api/small-model/foundation/model/checkpoint-8/execute-ast`, auth({ method: 'POST', body: JSON.stringify({ skillId: 'rename-legacy-name', path: 'src/value.mjs', source: 'const legacyName = 1;' }) }));
  assert.equal(ast.status, 200);
  assert.match((await ast.json()).output, /canonicalName/);
  const constraint = await fetch(`${service.url}/api/small-model/foundation/model/checkpoint-8/execute-constraint`, auth({ method: 'POST', body: JSON.stringify({ skillId: 'bounded-test-plan' }) }));
  assert.equal(constraint.status, 200);
  assert.equal((await constraint.json()).sat.status, 'sat');
});
