import { atomicWriteJson, freeze, readJson, sha256 } from './native-runtime-utils.mjs';
export class KanbanRuntime {
  constructor({ file, clock = () => Date.now() } = {}) { if (!file) throw new TypeError('file is required'); this.file = file; this.clock = clock; this.cards = new Map(); this.events = []; this.headSha256 = '0'.repeat(64); this.writeChain = Promise.resolve(); }
  async open() { const saved = await readJson(this.file, { cards: [], events: [], headSha256: '0'.repeat(64) }); this.cards = new Map(saved.cards.map((card) => [card.id, card])); this.events = saved.events; this.headSha256 = saved.headSha256; return this.snapshot(); }
  createCard(input) { const id = String(input?.id ?? '').trim(); if (!id || this.cards.has(id)) throw new Error(id ? `card already exists: ${id}` : 'card id is required'); return this.#mutate(id, null, { id, title: String(input.title ?? '').trim(), lane: String(input.lane ?? 'todo'), assignee: String(input.assignee ?? ''), version: 1, updatedAtMs: this.clock() }, 'created'); }
  async moveCard(id, { lane, expectedVersion } = {}) { const current = this.#get(id); if (Number(expectedVersion) !== current.version) throw new Error(`version conflict for card ${id}`); return this.#mutate(id, current, { ...current, lane: String(lane ?? current.lane), version: current.version + 1, updatedAtMs: this.clock() }, 'moved'); }
  getCard(id) { return freeze({ ...this.#get(id) }); }
  snapshot() { return freeze({ schema: 'nolane.kanban.snapshot.v1', cards: freeze([...this.cards.values()].map((v) => freeze({ ...v })).sort((a, b) => a.id.localeCompare(b.id))), events: this.events.length, headSha256: this.headSha256 }); }
  #get(id) { const card = this.cards.get(String(id)); if (!card) throw new Error(`unknown card: ${id}`); return card; }
  #mutate(id, previous, next, type) { if (!next.title) throw new TypeError('card title is required'); const base = { schema: 'nolane.kanban.event.v1', sequence: this.events.length + 1, type, cardId: id, previousVersion: previous?.version ?? 0, version: next.version, lane: next.lane, timestampMs: this.clock(), previousSha256: this.headSha256 }; const event = freeze({ ...base, receiptSha256: sha256(base) }); this.headSha256 = event.receiptSha256; this.cards.set(id, freeze(next)); this.events.push(event); this.writeChain = this.writeChain.catch(() => {}).then(() => atomicWriteJson(this.file, { cards: [...this.cards.values()], events: this.events, headSha256: this.headSha256 })); return this.writeChain.then(() => this.getCard(id)); }
}
