from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if text.count(old) != 1:
        raise SystemExit(f"unexpected {label} authority shape: {text.count(old)} matches")
    return text.replace(old, new)


# Home: convert disabled prerequisites and runtime failures into explicit next valid actions.
home = Path('ui-v3/views/home/home-view.mjs')
s = home.read_text()
anchor = "  const runtimeStatus = selectedModelReady ? providerStatus : (model.language === 'vi' ? 'Model đã chọn chưa sẵn sàng. Hãy chọn model khác hoặc đăng nhập provider đó.' : 'Selected model is not ready. Choose another model or sign in to its provider.');\n  const quick = ["
insert = "  const runtimeStatus = selectedModelReady ? providerStatus : (model.language === 'vi' ? 'Model đã chọn chưa sẵn sàng. Hãy chọn model khác hoặc đăng nhập provider đó.' : 'Selected model is not ready. Choose another model or sign in to its provider.');\n  const readiness = [];\n  if (!model.projects.length) readiness.push({ icon: 'folder', title: model.language === 'vi' ? 'Cần một dự án' : 'Project required', text: model.language === 'vi' ? 'Thêm thư mục hoặc kho mã để Nolane có không gian làm việc.' : 'Add a folder or repository so Nolane has a workspace.', href: '#/projects', action: model.language === 'vi' ? 'Thêm dự án' : 'Add project' });\n  if (!providersReady) readiness.push({ icon: 'model', title: model.language === 'vi' ? 'Cần provider' : 'Provider required', text: model.language === 'vi' ? 'Kết nối ít nhất một provider sẵn sàng trước khi chạy nhiệm vụ.' : 'Connect at least one ready provider before running a mission.', href: '#/settings?section=models', action: model.language === 'vi' ? 'Thiết lập provider' : 'Set up provider' });\n  else if (!selectedModelReady) readiness.push({ icon: 'warning', title: model.language === 'vi' ? 'Model chưa sẵn sàng' : 'Model not ready', text: runtimeStatus, href: '#/settings?section=models', action: model.language === 'vi' ? 'Kiểm tra model' : 'Review model' });\n  const readinessHtml = readiness.length ? `<div class=\"home-readiness\" role=\"region\" aria-label=\"${model.language === 'vi' ? 'Điều kiện để bắt đầu nhiệm vụ' : 'Mission prerequisites'}\">${readiness.map((item) => `<div class=\"home-readiness__item\"><span aria-hidden=\"true\">${icon(item.icon,{size:15})}</span><div><strong>${esc(item.title)}</strong><small>${esc(item.text)}</small></div><a href=\"${item.href}\" data-route=\"${item.href.slice(1)}\">${esc(item.action)} ${icon('arrow',{size:13})}</a></div>`).join('')}</div>` : '';\n  const quick = ["
s = replace_once(s, anchor, insert, 'Home runtime status')
old = "      </form>${model.error?`<div class=\"home-error\" role=\"alert\">${icon('warning',{size:16})}<span>${esc(model.error)}</span></div>`:''}\n    </div>"
new = "      </form>${readinessHtml}${model.error?`<div class=\"home-error\" role=\"alert\">${icon('warning',{size:16})}<span>${esc(model.error)}</span><button type=\"button\" data-home-action=\"retry\">${model.language==='vi'?'Thử lại':'Retry'}</button></div>`:''}\n    </div>"
s = replace_once(s, old, new, 'Home composer tail')
home.write_text(s)

# Projects: preserve current grid/activity architecture and add missing state semantics.
projects = Path('ui-v3/views/projects/project-view.mjs')
s = projects.read_text()
trust_anchor = "function trustTone(trust) {\n  return trust === 'trusted' ? 'success' : trust === 'blocked' ? 'danger' : 'warning';\n}\n"
trust_insert = trust_anchor + "\nfunction projectTrustLabel(trust, language = 'en') {\n  const value = String(trust ?? 'unknown').toLowerCase();\n  if (language === 'vi') return ({ trusted: 'Tin cậy', blocked: 'Bị chặn', manual: 'Thủ công', local: 'Cục bộ', untrusted: 'Chưa tin cậy', unknown: 'Chưa rõ' })[value] ?? String(trust ?? 'Chưa rõ');\n  return ({ trusted: 'Trusted', blocked: 'Blocked', manual: 'Manual', local: 'Local', untrusted: 'Untrusted', unknown: 'Unknown' })[value] ?? String(trust ?? 'Unknown');\n}\n"
s = replace_once(s, trust_anchor, trust_insert, 'Projects trust semantics')
s = replace_once(s, "<small>${esc(project.trust)}</small>", "<small>${esc(projectTrustLabel(project.trust, language).toUpperCase())}</small>", 'Projects trust label')
s = replace_once(s, "  const query = String(state.query ?? '').toLowerCase();\n  const projects = (state.projects ?? []).filter((project) => !query || `${project.name} ${project.path} ${project.id}`.toLowerCase().includes(query));", "  const rawQuery = String(state.query ?? '').trim();\n  const query = rawQuery.toLowerCase();\n  const projects = (state.projects ?? []).filter((project) => !query || `${project.name} ${project.path} ${project.id}`.toLowerCase().includes(query));", 'Projects query normalization')
s = replace_once(s, "    ? `<div class=\"page-loading\"><span class=\"spinner\"></span>${t('common.loading', language)}</div>`", "    ? `<div class=\"page-loading\" aria-busy=\"true\"><span class=\"spinner\"></span><span role=\"status\" aria-live=\"polite\">${t('common.loading', language)}</span></div>`", 'Projects loading state')
s = replace_once(s, "      ? `<div class=\"page-error\">${icon('warning', { size: 18 })}<span>${esc(state.error)}</span></div>`", "      ? `<div class=\"page-error projects-error\">${icon('warning', { size: 18 })}<span role=\"alert\">${esc(state.error)}</span><button type=\"button\" data-project-action=\"retry\">${language === 'vi' ? 'Thử lại' : 'Retry'}</button></div>`", 'Projects error state')
old_empty = "      : !projects.length\n        ? `<div class=\"empty-state page-empty\"><span>${icon('projects', { size: 20 })}</span><strong>${language === 'vi' ? 'Chưa có dự án' : 'No projects yet'}</strong><p>${t('projects.empty', language)}</p></div>`"
new_empty = "      : !projects.length\n        ? rawQuery\n          ? `<div class=\"empty-state page-empty page-empty--search\"><span>${icon('search', { size: 20 })}</span><strong>${language === 'vi' ? 'Không có dự án phù hợp' : 'No matching projects'}</strong><p>${language === 'vi' ? `Không tìm thấy dự án nào cho “${esc(rawQuery)}”.` : `No projects match “${esc(rawQuery)}”.`}</p><button type=\"button\" data-project-action=\"clear-search\">${language === 'vi' ? 'Xóa tìm kiếm' : 'Clear search'}</button></div>`\n          : `<div class=\"empty-state page-empty\"><span>${icon('projects', { size: 20 })}</span><strong>${language === 'vi' ? 'Chưa có dự án' : 'No projects yet'}</strong><p>${t('projects.empty', language)}</p><button type=\"button\" data-project-action=\"add\">${language === 'vi' ? 'Thêm dự án' : 'Add project'}</button></div>`"
s = replace_once(s, old_empty, new_empty, 'Projects empty/search state')
old_search = "<input type=\"search\" data-project-search placeholder=\"${language === 'vi' ? 'Tìm dự án…' : 'Search projects…'}\" value=\"${esc(state.query ?? '')}\">"
new_search = "<input type=\"search\" data-project-search data-preserve-key=\"projects-search\" autocomplete=\"off\" spellcheck=\"false\" placeholder=\"${language === 'vi' ? 'Tìm dự án…' : 'Search projects…'}\" value=\"${esc(state.query ?? '')}\">"
s = replace_once(s, old_search, new_search, 'Projects search input')
old_toggle = "<button type=\"button\" data-project-view=\"grid\" aria-pressed=\"${view === 'grid'}\""
new_toggle = "<button type=\"button\" data-project-view=\"grid\" data-preserve-key=\"project-view-grid\" aria-pressed=\"${view === 'grid'}\""
s = replace_once(s, old_toggle, new_toggle, 'Projects grid toggle')
old_toggle = "<button type=\"button\" data-project-view=\"activity\" aria-pressed=\"${view === 'activity'}\""
new_toggle = "<button type=\"button\" data-project-view=\"activity\" data-preserve-key=\"project-view-activity\" aria-pressed=\"${view === 'activity'}\""
s = replace_once(s, old_toggle, new_toggle, 'Projects activity toggle')
projects.write_text(s)

# Use the existing generic rerenderView focus/selection authority instead of duplicating it.
app = Path('ui-v3/app.mjs')
s = app.read_text()
old_route = "router.register({ id: 'projects', pattern: /^\\/projects(?:\\?.*)?$/, title: 'Projects', load: async () => {\n  const { createProjectsController, renderProjectsView } = await import('./views/projects/project-view.mjs');const controller=createProjectsController({api,language:cachedPreferences.language});await controller.load();let root=null;const view={render:()=>renderProjectsView(controller.snapshot()),mount(node){root=node;const input=e=>{if(e.target.matches('[data-project-search]')){controller.setQuery(e.target.value);rerenderView(root,view);}};const click=e=>{const mode=e.target.closest('[data-project-view]');if(mode){controller.setView(mode.dataset.projectView);rerenderView(root,view);return;}if(e.target.closest('[data-project-action=\"add\"]')){window.dispatchEvent(new CustomEvent('nolane:project-create-requested',{detail:{source:'projects-view'}}));}};root.addEventListener('input',input);root.addEventListener('click',click);return()=>{root.removeEventListener('input',input);root.removeEventListener('click',click)}}};return view;\n} });"
new_route = "router.register({ id: 'projects', pattern: /^\\/projects(?:\\?.*)?$/, title: 'Projects', load: async () => {\n  const { createProjectsController, renderProjectsView } = await import('./views/projects/project-view.mjs');const controller=createProjectsController({api,language:cachedPreferences.language});await controller.load();let root=null;const focusSearch=()=>requestAnimationFrame(()=>root?.querySelector('[data-project-search]')?.focus({preventScroll:true}));const view={render:()=>renderProjectsView(controller.snapshot()),mount(node){root=node;const input=e=>{if(e.target.matches('[data-project-search]')){controller.setQuery(e.target.value);rerenderView(root,view,{preserve:e.target});}};const click=async e=>{const mode=e.target.closest('[data-project-view]');if(mode){controller.setView(mode.dataset.projectView);rerenderView(root,view,{preserve:mode});return;}const action=e.target.closest('[data-project-action]')?.dataset.projectAction;if(action==='add'){window.dispatchEvent(new CustomEvent('nolane:project-create-requested',{detail:{source:'projects-view'}}));return;}if(action==='clear-search'){controller.setQuery('');rerenderView(root,view);focusSearch();return;}if(action==='retry'){await controller.load();rerenderView(root,view);focusSearch();}};root.addEventListener('input',input);root.addEventListener('click',click);return()=>{root.removeEventListener('input',input);root.removeEventListener('click',click)}}};return view;\n} });"
s = replace_once(s, old_route, new_route, 'Projects route wiring')
home_click = "      const click = async (event) => {\n        const selectedSkillRemove=event.target.closest('[data-selected-skill-remove]');"
home_click_new = "      const click = async (event) => {\n        const homeAction=event.target.closest('[data-home-action]')?.dataset.homeAction; if(homeAction==='retry'){const value=root.querySelector('#objective')?.value??'';await controller.load();render({textareaValue:value,focus:true});return;}\n        const selectedSkillRemove=event.target.closest('[data-selected-skill-remove]');"
s = replace_once(s, home_click, home_click_new, 'Home retry wiring')
app.write_text(s)

# Bounded styles: recovery actions stay instrument-like rather than becoming new cards.
home_css = Path('ui-v3/styles/pages/home.css')
home_css.write_text(home_css.read_text() + '''\n.home-readiness{display:grid;gap:0;width:min(960px,100%);margin-top:12px;border-block:1px solid var(--instrument-rule)}\n.home-readiness__item{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;min-height:var(--density-row-height);padding:9px 2px;color:var(--text-secondary)}\n.home-readiness__item+.home-readiness__item{border-top:1px solid var(--border-faint)}\n.home-readiness__item>span{display:grid;place-items:center;width:30px;height:30px;color:var(--instrument-trace)}\n.home-readiness__item>div{display:grid;min-width:0;gap:2px}.home-readiness__item strong{color:var(--text-primary);font-size:11px}.home-readiness__item small{color:var(--text-secondary);font-size:10px;line-height:1.45}\n.home-readiness__item>a{display:flex;align-items:center;gap:4px;color:var(--text-secondary);font-size:10px;text-decoration:none}.home-readiness__item>a:hover,.home-readiness__item>a:focus-visible{color:var(--text-primary)}\n.home-error button{margin-left:auto;padding:5px 9px;border:1px solid color-mix(in srgb,var(--nolane-danger) 35%,var(--border-default));border-radius:8px;background:transparent;color:var(--text-primary)}\n@media(max-width:680px){.home-readiness__item{grid-template-columns:auto minmax(0,1fr)}.home-readiness__item>a{grid-column:2;justify-self:start}}\n''')

projects_css = Path('ui-v3/styles/pages/projects.css')
projects_css.write_text(projects_css.read_text() + '''\n.projects-error{gap:10px}.projects-error button,.page-empty--search button,.projects-page>.page-empty button{justify-self:center;padding:6px 10px;border:1px solid var(--border-subtle);border-radius:8px;background:var(--surface-raised);color:var(--text-secondary)}\n.projects-error button:hover,.page-empty--search button:hover,.projects-page>.page-empty button:hover{border-color:var(--border-default);color:var(--text-primary)}\n.page-empty--search>span{color:var(--text-secondary)}\n''')
